apiVersion: v1
kind: ConfigMap
metadata:
  name: dhcp-config
  namespace: default
data:
  dhcpd.conf: |
    default-lease-time 600;
    max-lease-time 7200;
    subnet 12.12.12.0 netmask 255.255.255.0 {
      range 12.12.12.100 12.12.12.150;
      option routers 12.12.12.1;
      option domain-name-servers 8.8.8.8, 8.8.4.4;
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhcp-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dhcp-server
  template:
    metadata:
      labels:
        app: dhcp-server
    spec:
      containers:
      - name: dhcp-server
        image: networkboot/dhcpd:latest
        args:
          - "-cf"
          - "/etc/dhcp/dhcpd.conf"
          - "-f"
        volumeMounts:
        - name: dhcp-config-volume
          mountPath: /etc/dhcp
      volumes:
      - name: dhcp-config-volume
        configMap:
          name: dhcp-config
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet # Usar resolución de nombres compatible con hostNetwork
      securityContext:
        capabilities:
          add:
            - NET_ADMIN

---
apiVersion: v1
kind: Service
metadata:
  name: dhcp-server
  namespace: default
spec:
  selector:
    app: dhcp-server
  ports:
    - protocol: UDP
      port: 67
      targetPort: 67
  type: ClusterIP

